In [6]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
base = "/home/chenze/data_gpfs02/CAMELS_multifield/raw_data/"
simcode = "IllustrisTNG"
alias = "TNG"

# these have length 1000
sim_param = np.loadtxt(f'{base}/params_LH_{simcode}.txt', unpack=True)
sim_param = np.repeat(sim_param, 15, axis=1).reshape(6, 15000).T

M_img = np.load(f'{base}/Maps_Mtot_{simcode}_LH_z=0.00.npy').reshape(15000, 256, 256)
M_img = np.log10(M_img)
print(f"Maximum of log10(M_img) = {M_img.max():.8f}")
print(f"Minimum of log10(M_img) = {M_img.min():.8f}")
M_img = (M_img - M_img.min()) / (M_img.max() - M_img.min())

P_img = np.load(f'{base}/Maps_P_{simcode}_LH_z=0.00.npy').reshape(15000, 256, 256)
P_img = np.log10(P_img)
print(f"Maximum of log10(P_img) = {P_img.max():.8f}")
print(f"Minimum of log10(P_img) = {P_img.min():.8f}")
P_img = (P_img - P_img.min()) / (P_img.max() - P_img.min())

imgs_all = np.zeros([15000, 2, 256, 256], dtype=np.float32)
imgs_all[:,0,:,:] = M_img
imgs_all[:,1,:,:] = P_img

Maximum of log10(M_img) = 15.50328541
Minimum of log10(M_img) = 9.66257858
Maximum of log10(P_img) = 13.42540932
Minimum of log10(P_img) = 0.74502987


In [8]:
np.save("/home/chenze/data_gpfs02/CAMELS_multifield/dataset/compiled_img_TNG.npy", imgs_all)
np.save("/home/chenze/data_gpfs02/CAMELS_multifield/dataset/compiled_params_TNG.npy", sim_param)

-----

In [13]:
M_min = 9.66257858
M_max = 15.50328541
P_min = 0.74502987
P_max = 13.42540932

In [14]:
import numpy as np

# change these according to your path
base = "/home/chenze/data_gpfs02/CAMELS_multifield/raw_data/"
simcode = "IllustrisTNG"
alias = "TNG"
save_path = "/home/chenze/data_gpfs02/CAMELS_multifield/dataset/"

# the param
sim_param = np.loadtxt(f'{base}/params_LH_{simcode}.txt', unpack=True)
sim_param = np.repeat(sim_param, 15, axis=1).reshape(6, 15000).T

# read & preprocessing img data
M_img = np.load(f'{base}/Maps_Mtot_{simcode}_LH_z=0.00.npy').reshape(15000, 256, 256)
M_img = np.log10(M_img)
print(f"Maximum of log10(M_img) = {M_img.max():.8f}") # the normalization should be
print(f"Minimum of log10(M_img) = {M_img.min():.8f}") # same for two prescriptions!
M_img = (M_img - M_min) / (M_max - M_min)

P_img = np.load(f'{base}/Maps_P_{simcode}_LH_z=0.00.npy').reshape(15000, 256, 256)
P_img = np.log10(P_img)
print(f"Maximum of log10(P_img) = {P_img.max():.8f}")
print(f"Minimum of log10(P_img) = {P_img.min():.8f}")
P_img = (P_img - P_min) / (P_max - P_min)

# combine the data
imgs_all = np.zeros([15000, 2, 256, 256], dtype=np.float32)
imgs_all[:,0,:,:] = M_img
imgs_all[:,1,:,:] = P_img

np.save(save_path+f"compiled_img_{alias}.npy", imgs_all)
np.save(save_path+f"compiled_params_{alias}.npy", sim_param)

Maximum of log10(M_img) = 15.50328541
Minimum of log10(M_img) = 9.66257858
Maximum of log10(P_img) = 13.42540932
Minimum of log10(P_img) = 0.74502987


In [16]:
import numpy as np

# change these according to your path
base = "/home/chenze/data_gpfs02/CAMELS_multifield/raw_data/"
simcode = "SIMBA"
alias = "SIMBA"
save_path = "/home/chenze/data_gpfs02/CAMELS_multifield/dataset/"

# the param
sim_param = np.loadtxt(f'{base}/params_LH_{simcode}.txt', unpack=True)
sim_param = np.repeat(sim_param, 15, axis=1).reshape(6, 15000).T

# read & preprocessing img data
M_img = np.load(f'{base}/Maps_Mtot_{simcode}_LH_z=0.00.npy').reshape(15000, 256, 256)
M_img = np.log10(M_img)
M_img = (M_img - M_img.min()) / (M_img.max() - M_img.min())

P_img = np.load(f'{base}/Maps_P_{simcode}_LH_z=0.00.npy').reshape(15000, 256, 256)
P_img = np.log10(P_img)
print(f"Maximum of log10(P_img) = {P_img.max():.8f}")
print(f"Minimum of log10(P_img) = {P_img.min():.8f}")
P_img = (P_img - P_img.min()) / (P_img.max() - P_img.min())

# combine the data
imgs_all = np.zeros([15000, 2, 256, 256], dtype=np.float32)
imgs_all[:,0,:,:] = M_img
imgs_all[:,1,:,:] = P_img

np.save(save_path+f"compiled_img_{alias}.npy", imgs_all)
np.save(save_path+f"compiled_params_{alias}.npy", sim_param)

Maximum of log10(P_img) = 13.43841743
Minimum of log10(P_img) = -0.21077976


In [7]:
np.random.seed(114514)
shuffle = np.arange(15000)
np.random.shuffle(shuffle)

In [8]:
np.random.seed(114514)
shuffle = np.arange(15000)
np.random.shuffle(shuffle)

img_list = img_list[shuffle]
lab_list = lab_list[shuffle]

NameError: name 'img_list' is not defined

In [9]:

img_list = np.load("/home/chenze/data_gpfs02/CAMELS_multifield/dataset/compiled_img_TNG.npy")
lab_list = np.load("/home/chenze/data_gpfs02/CAMELS_multifield/dataset/compiled_params_TNG.npy")

np.random.seed(114514)
shuffle = np.arange(15000)
np.random.shuffle(shuffle)

img_list = img_list[shuffle]
lab_list = lab_list[shuffle]

In [10]:
lab_list

array([[0.1226 , 0.6518 , 0.27586, 2.47942, 1.9066 , 1.90924],
       [0.4574 , 0.899  , 0.54563, 0.68113, 1.29684, 1.32593],
       [0.3966 , 0.6074 , 1.5305 , 0.61132, 0.98146, 1.07848],
       ...,
       [0.2782 , 0.9062 , 1.95884, 2.27521, 1.74957, 0.62201],
       [0.4834 , 0.7282 , 3.22657, 3.78948, 1.09051, 0.51656],
       [0.1074 , 0.8474 , 1.03814, 0.45946, 0.7626 , 1.70882]])

In [1]:
import os,sys
import numpy as np
import time

import torch
from torch import nn
from torch.utils.data import DataLoader

from dataset import CosDataset, train_tfm, test_tfm
from model import CNN_cosmo

rng_seed = 114514
training_ratio = 0.7
valid_ratio = 0.2
test_ratio = 0.1
batch_size = 32

/home/chenze/env/miniconda3/envs/torch_env/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
device = "cpu"

In [3]:

img_list = np.load("/home/chenze/data_gpfs02/CAMELS_multifield/dataset/compiled_img_TNG.npy")
img_list = torch.tensor(img_list)
lab_list = np.load("/home/chenze/data_gpfs02/CAMELS_multifield/dataset/compiled_params_TNG.npy")
lab_list = torch.tensor(lab_list)


np.random.seed(114514)
shuffle = np.arange(15000)
np.random.shuffle(shuffle)

img_list = img_list[shuffle]
lab_list = lab_list[shuffle]

In [4]:
    np.random.seed(rng_seed)
    shuffle = np.arange(img_list.shape[0])
    np.random.shuffle(shuffle)
    
    img_list = img_list[shuffle]
    lab_list = lab_list[shuffle]
    
    len_training = int(len(img_list) * training_ratio)
    len_valid = int(len(img_list) * training_ratio) + int(len(img_list) * valid_ratio)
    
    train_set = CosDataset(img_list[:len_training], lab_list[:len_training], tfm=train_tfm)
    train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True, pin_memory=True)
    valid_set = CosDataset(img_list[len_training:len_valid], lab_list[len_training:len_valid], tfm=test_tfm)
    valid_loader = DataLoader(valid_set, batch_size=batch_size, shuffle=True, pin_memory=True)
    test_set  = CosDataset(img_list[len_valid:], lab_list[len_valid:], tfm=test_tfm)
    test_loader = DataLoader(test_set, batch_size=batch_size, shuffle=True, pin_memory=True)

In [5]:
        for step, (batch_data, batch_targ) in enumerate(valid_loader):
            batch_data = batch_data.type(torch.FloatTensor).to(device)
            batch_targ = batch_targ.type(torch.FloatTensor).to(device)

In [7]:
torch.randint(0, 256, size=(3, 10, 10), dtype=torch.uint8)

tensor([[[ 35, 144,  26,  35,  48,  67, 176,  47, 126, 233],
         [195,   4, 107,  27, 248, 207,  20, 253,  46, 134],
         [123,  94,  57,  26, 101,  70,  18, 212, 198,  87],
         [ 30, 191,  40, 136,  37, 251, 110, 203, 230, 113],
         [219, 111, 123,  66,  81, 108, 130, 125,  90, 161],
         [216, 132, 201, 131,  94, 217,  50,  64, 181,  27],
         [163,  33, 136, 138, 153,  18,  72,   9, 240, 223],
         [114, 164, 121, 117,  17,  11, 184,  41,  41,  45],
         [ 41,  19, 116, 134,  31, 182,  72, 223, 243, 148],
         [182, 109, 194,  44, 209, 225, 183, 245, 217, 113]],

        [[106,  57, 123,  17, 222, 228, 110,  40, 125,  58],
         [180,  92,  96,  17, 123,  71, 189, 150,  32, 135],
         [ 89,  73,  77, 212, 243,  51,  34, 124, 217,   4],
         [ 91,  68, 239, 108, 214,  77,  91, 169,  79, 251],
         [ 70,  78,  94,  74, 111,  92,  66, 185, 233, 255],
         [164, 127, 161, 136, 229, 154, 168, 127, 188,  39],
         [225, 230, 16

In [9]:
torch.tensor([1,])

tensor([1])